from .multi_armed_bandit import MultiArmedBandit
from .Discounted_multi_armed_bandit import DiscountedMultiArmedBandit
from .gaussian_bandit import GaussianBandit
from .bernoulli_bandit import BernoulliBandit
from .bernoulli_Discounted_bandit import BernoulliDiscountedBandit
from .gaussian_Discounted_bandit import GaussianDiscountedBandit
from .bernoulli_replay_bandit import BernoulliReplayBandit
from .gaussian_replay_bandit import GaussianReplayBandit
